const mongoose = require('mongoose');

const attendanceSchema = new mongoose.Schema(
  {
    employee: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Employee',
      required: true,
    },

    // Normalized to midnight - the calendar day this record belongs to.
    date: {
      type: Date,
      required: true,
    },

    clockIn: {
      type: Date,
      required: true,
    },
    clockOut: {
      type: Date,
      default: null,
    },

    breakMinutes: {
      type: Number,
      default: 0,
      min: 0,
    },

    // Auto-computed when both clockIn and clockOut are present (see
    // controller), but can be left null if only clockIn was recorded
    // by the device (e.g. employee forgot to scan out).
    workingHours: {
      type: Number,
      default: null,
    },

    status: {
      type: String,
      enum: ['present', 'late', 'half-day', 'absent'],
      default: 'present',
    },

    // Tracks which HR user actually entered this record - useful for
    // an audit trail, since these are manually keyed in from device
    // exports rather than generated by the system itself.
    recordedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
  },
  { timestamps: true }
);

attendanceSchema.index({ employee: 1, date: 1 }, { unique: true });

module.exports = mongoose.model('Attendance', attendanceSchema);